### ISSUE TITLE
Remove or geocode sessions with long/lat missing

### ISSUE THREAD

**Issue by ryanbaumann** [ibm-cds-labs/cognitive-event-finder#1]
# Problem

Geo-located SXSW events are shows at 0/0 long/lat if they do not have proper geolocation.

![](https://cl.ly/2k3C3D3p140u/download/Image%202017-02-10%20at%2012.55.11%20PM.png)

# Solution options

1. Filter out location 0/0 values
2. Geocode session based on building address

**Comment by isc-rsingh** [comment]
no longer needed -- no bad data!
