### ISSUE TITLE
Suggestion results

### ISSUE THREAD

**Issue by isc-rsingh** [ibm-cds-labs/cognitive-event-finder#41]
Search for events starting within 30 minutes with a preference for those containing IBM or mapping in the description

**Comment by markwatsonatx** [comment]
@rajrsingh We need to revisit this. There are only 6 events in 10 days that match IBM or map.

**Comment by isc-rsingh** [comment]
@markwatsonatx how about also adding watson OR cognitive OR machine learning OR data science OR analytics

**Comment by markwatsonatx** [comment]
This has been addressed. The search terms are configurable in an environment variable which is currently set as follows:

`SUGGESTED_SEARCH_TERMS=ibm,map,cognitive,machine learning,data science,analytics`

**Comment by isc-rsingh** [comment]
Looks great!
