### ISSUE TITLE
Make sure search is only for the current day

### ISSUE THREAD

**Issue by isc-rsingh** [ibm-cds-labs/cognitive-event-finder#9]
and doesn't include events already over

**Comment by markwatsonatx** [comment]
This has been fixed and is configurable with a number of environment variables:

`WARP_TIME_HOURS=96`: Allows you to test from a point in time in the future. For example, if this is set to 96 then the start of the time window will be the current time + 96 hours.

`SEARCH_TIME_HOURS=8`: The end of the time window. The start of the time window is current time + WARP_TIME_HOURS

`MAX_SEARCH_TIME_HOURS=248`: If no results are found in a time window the system will double the time window until results or found, or the time window exceeds this value.

**Comment by isc-rsingh** [comment]
Excellent stuff
